CREATE TABLE IF NOT EXISTS Clients (
    id INTEGER PRIMARY KEY,
    creator TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Providers (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Relations (
    id INTEGER PRIMARY KEY,
    address TEXT NOT NULL,
    provider_id INTEGER NOT NULL,
    client_id INTEGER NOT NULL,
    submission_id TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS MockKYC (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    yearOfBirth INTEGER NOT NULL,
    country TEXT NOT NULL,
    provider_id INTEGER NOT NULL,
    submission_id TEXT NOT NULL,
    creditScore INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
